=== goofwear/stepmania/stepmania/Docs/Lua.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.stepmania.com"
 xmlns="http://www.stepmania.com"
 elementFormDefault="qualified">

<xs:element name="Lua">
	<xs:complexType>
		<xs:all>
			<xs:element name="Singletons" type="Singletons" />
			<xs:element name="Classes" type="Classes" />
			<xs:element name="GlobalFunctions" type="GlobalFunctions" />
			<xs:element name="Enums" type="Enums" />
			<xs:element name="Constants" type="Constants" />
			<xs:element name="Date" type="xs:date" />
			<xs:element name="Version" type="xs:string" />
		</xs:all>
	</xs:complexType>
</xs:element>


<xs:element name="Documentation">
	<xs:complexType>
		<xs:all>
			<xs:element name="Classes" type="Classes" />
			<xs:element name="GlobalFunctions" type="GlobalFunctions" />
		</xs:all>
	</xs:complexType>
</xs:element>


<xs:complexType name="Singletons">
	<xs:sequence>
		<xs:element name="Singleton" minOccurs="0" maxOccurs="unbounded">
			<xs:complexType>
				<xs:attribute name="name" type="xs:string" use="required" />
				<xs:attribute name="class" type="xs:string" use="required" />
			</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>


<xs:complexType name="Classes">
	<xs:sequence>
		<xs:element name="Class" minOccurs="0" maxOccurs="unbounded">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="Function" type="Function"
					 minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
				<xs:attribute name="name" type="xs:string" use="required" />
				<xs:attribute name="base" type="xs:string" use="optional" />
			</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>


<xs:complexType name="GlobalFunctions">
	<xs:sequence>
		<xs:element name="Function" type="Function"
		 minOccurs="0" maxOccurs="unbounded" />
	</xs:sequence>
</xs:complexType>


<xs:complexType name="Function" mixed="true">
	<xs:sequence>
		<xs:element name="Link" minOccurs="0" maxOccurs="unbounded" />
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required" />
	<xs:attribute name="return" type="xs:string" use="optional" />
	<xs:attribute name="arguments" type="xs:string" use="optional" />
</xs:complexType>

<xs:complexType name="Link" mixed="true">
	<xs:attribute name="function" type="xs:string" use="optional" />
	<xs:attribute name="class" type="xs:string" use="optional" />
</xs:complexType>

<xs:complexType name="Enums">
	<xs:sequence>
		<xs:element name="Enum" minOccurs="0" maxOccurs="unbounded">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="EnumValue" type="Constant"
					 minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
				<xs:attribute name="name" type="xs:string" use="required" />
			</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>


<xs:complexType name="Constants">
	<xs:sequence>
		<xs:element name="Constant" type="Constant"
		 minOccurs="0" maxOccurs="unbounded" />
	</xs:sequence>
</xs:complexType>


<xs:complexType name="Constant">
	<xs:attribute name="name" type="xs:string" use="required" />
	<xs:attribute name="value" type="xs:string" use="required" />
</xs:complexType>
</xs:schema>

=== goofwear/stepmania/stepmania/Docs/LuaDocumentation.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!-- Before checking the documentation in, make sure that it validates by
     going to http://tools.decisionsoft.com/schemaValidate/ and using
     Lua.xsd for the XML Schema and this file for the XML Instanace. -->

<Documentation xmlns='http://www.stepmania.com' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='http://www.stepmania.com Lua.xsd'>
<!-- Global functions -->
<GlobalFunctions>
<Function name='Basename' return='string' arguments='path'>
	Returns the base name of file path.
</Function>
<Function name='FormatNumberAndSuffix' return='string' arguments='integer'>
	Returns the number passed to the function followed by its suffix (&quot;th&quot;, &quot;nd&quot;, and so on).
</Function>
</GlobalFunctions>

<!-- Classes -->
<Classes>
<Class name='Actor'>
	<Function name='x' return='void' arguments='xPos'>
		Set the x position of the Actor.
	</Function>
	<Function name='y' return='void' arguments='yPos'>
		Set the y position of the Actor.
	</Function>
	<Function name='z' return='void' arguments='zPos'>
		Set the z position of the Actor.
	</Function>
</Class>
<Class name='Song'>
	<Function name='GetDisplayArtist' return='string' arguments='none'>
		Returns the displayed artist of the song.
	</Function>
	<Function name='GetDisplayFullTitle' return='string' arguments='none'>
		Returns the displayed full title of the song, including subtitle.
	</Function>
	<Function name='GetDisplayMainTitle' return='string' arguments='none'>
		Returns the displayed main title of the song.
	</Function>
	<Function name='GetTranslitArtist' return='string' arguments='none'>
		Returns the transliterated artist of the song.
	</Function>
	<Function name='GetTranslitFullTitle' return='string' arguments='none'>
		Returns the transliterated full title of the song, including subtitle.
	</Function>
	<Function name='GetTranslitMainTitle' return='string' arguments='none'>
		Returns the transliterated main title of the song.
	</Function>
	<Function name='IsLong' return='bool' arguments='none'>
		Returns true if the song meets the criteria for a &quot;Long Version&quot;.
	</Function>
	<Function name='IsMarathon' return='bool' arguments='none'>
		Returns true if the song meets the criteria for &quot;Marathon&quot; length.
	</Function>
</Class>
</Classes>
</Documentation>
